name: Trigger TF ECR creation workflow
on:
  workflow_dispatch:

jobs:
  trigger-deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ECR creation workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAC_TOKEN_TERRAFORM }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/aalexlit/capitalbikeshare-service-terraform/actions/workflows/apply.yml/dispatches \
          -d '{"inputs":{"environment":"stg","destroy":"false","ecr-only":"true"}}'
