name: Test calling TF workflow
on:
  workflow_dispatch:

jobs:
  deploy-infra:
    uses: aaalexlit/capitalbikeshare-service-terraform/.github/workflows/apply.yml@main
    with:
      environment: 'stg'
      ecr-only: false
